### ISSUE TITLE
Arguments when creating a UDVD model (BlindVideoNet)

### ISSUE THREAD

**Issue by Scienceseb** [sreyas-mohan/udvd#1]
Hello, 
sorry but I'm not sure I understand the arguments when creating a UDVD model. Indeed, in your code it is written that BlindVideoNet takes: input channels_per_frame and out_channels. 

When I create the model I do `UDVD=BlindVideoNet(3,9)`, because I have three images and the images have 3 channels per frame and in total it's 9 channels. The tensor shape I give to UDVD is [8, 9, 512, 512] for [Batch_size, sequence_total_channel, H, W]. 

However, your code returns an error telling me `RuntimeError: Given groups=1, weight of size [48, 9, 3, 3], expected input[8, 6, 515, 514] to have 9 channels, but got 6 channels instead.`

 So I'm wondering what is the shape of the tensor that your network takes as input and what is the shape of the output. Thank you!

Kind regards,
Sébastien de Blois

**Comment by DevSheth** [comment]
Sorry, haven't added details in the README yet, will do it shortly. You can use `BlindVideoNetD1(channels_per_frame=3, out_channels=3)` for taking in 3 frame input (3 channels each) and getting a single frame output. I will add the post_processing and log-likelihood loss code usage shortly to the README. 

`BlindSpotNet` is the image denoiser (single frame). `BlindVideoNetD1` is a single denoising block taking as input the concatenation of 3 frames and `BlindVideoNet` is the standard UDVD which expects a 5 frame input.

**Comment by Scienceseb** [comment]
Thanks a lot it is working now.
