### ISSUE TITLE
Question about asymmetric convolutional filters that are vertically causal

### ISSUE THREAD

**Issue by hcy96** [sreyas-mohan/udvd#2]
Hi, thank you for your amazing work!

I do not catch the implementation of asymmetric convolutional filters that are vertically causal. Maybe I miss some information...

Could you please give me some hints about implementation  the asymmetric  convolutional filters that are vertically causal?

Thanks a lot

**Comment by sreyas-mohan** [comment]
Please look at `Conv` class defined here: https://github.com/sreyas-mohan/udvd/blob/7374e5bafde865c3a7ef11c5543d5c0b19da40af/models/udvd.py#L27

This is based on Section 2 of Ref. [22] in our paper.
