### ISSUE TITLE
Question about the speed of training

### ISSUE THREAD

**Issue by Scienceseb** [sreyas-mohan/udvd#3]
Hi thanks again for your great work!

I have a question regarding the speed during the training phase I found it a lot slower (5x) than an equally complex FastDVDNet model, UDVD has almost the same architecture as the FastDVDNet, so why is that? I know that the training scheme is completely different cause UDVD is self-supervised and FastDVDNet is supervised, but still it is a huge speed difference between both methods. 

Thanks a lot for your help.

**Comment by sreyas-mohan** [comment]
Thanks for your question. There are a couple of reasons:

1. Like you outlined,  UDVD and FastDVDNet follows a two stage architecture, with each stage using a UNet. However, in case of UDVD, these UNets are modified to contain an architectural blindspot. We achieve this by passing 4 rotated versions of the images (rotated by 0, 90, 180, 270) to this special UNet. So fora given input video, UDVD almost does 4x the computation than FastDVDNet, making our forward pass equivalent to almost 4x their forward pass (see Fig 2 and Section 3 in our paper,  and Ref. [22])

2. Depending on the noise model you are using, the loss function used in UDVD is more expensive to compute. This will add to the training complexity. 

Please let us know if you have any questions.

**Comment by Scienceseb** [comment]
Thanks a lot for that answer !
